version: '3'

services:
  pgs-db:
    image: postgres:latest
    container_name: pgs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=134qwefd
      - POSTGRES_DB=product
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/my_data
    restart: always

  backend:
    build:
      context: ./backend
    environment:
      DJANGO_DB_NAME: product
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: 134qwefd
      DJANGO_DB_HOST: pgs-db 
      DJANGO_DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - pgs-db 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
